version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 525158249545.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t esc-50-melspec-creator:latest ./melspecs/
      - docker tag esc-50-melspec-creator:latest 525158249545.dkr.ecr.us-west-2.amazonaws.com/esc-50-melspec-creator:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 525158249545.dkr.ecr.us-west-2.amazonaws.com/esc-50-melspec-creator:latest
      - export AWS_DEFAULT_REGION=us-west-2
      - aws eks update-kubeconfig --name arm5
      - pwd
      - kubectl delete -f melspecs/job.yml
      - kubectl apply -f melspecs/job.yml

