apiVersion: batch/v1
kind: Job
metadata:
  name: esc-50-melspecs
  namespace: audio
spec:
  ttlSecondsAfterFinished: 100
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccount: audio-sa
      containers:
      - name: esc-50-melspecs
        image: "525158249545.dkr.ecr.us-west-2.amazonaws.com/esc-50-melspec-creator"
        imagePullPolicy: Always
        env:
          - name: "AWS_REGION"
            value: "us-west-2"
        # resources:
        #   limits:
        #     memory: "2000Mi"
        #     cpu: "2"
      nodeSelector:
        kubernetes.io/arch: amd64
  backoffLimit: 20
